twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    globals:
        menu_service: '@App\Service\MenuService'
        option_service: '@App\Service\OptionService'


when@test:
    twig:
        strict_variables: true
